version: "3"

services:
  eti-sync-server:
    image: ghcr.io/poeschl/eti-sync-server
    # Required for not-cpu-burning downloads
    network_mode: host
    # Required for systemd
    privileged: true
    volumes:
      # Required for systemd
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

      # Uncomment the next line if you want a custom config
      #- ./eti-config.conf:/root/eti-config.conf

      # Comment the next line if you want docker to take care of the download data location.
      # Per default a new folder named 'lan' in the current directory will be created that will be used.
      - ./lan:/lan:rw
