services:
  eti-sync-server:
    image: ghcr.io/poeschl/eti-sync-server:${ETI_SYNC_SERVER_VERSION}
    depends_on:
      - resilio
    volumes:
      - "./eti-config.conf:/root/eti-config.conf"
      - "${RESILIO_SYNC_FOLDER}:/sync:z"

  resilio:
    image: linuxserver/resilio-sync:${RESILIO_VERSION}
    restart: unless-stopped
    # use the host network to support local multicast/broadcast discovery
    network_mode: host
    mem_limit: ${RESILIO_MEMORY_LIMIT}
    environment:
      PUID: ${USER_UID}
      PGID: ${USER_GID}
      TZ: ${RESILIO_TIMEZONE}
      IS_ONLINE: ${RESILIO_IS_ONLINE}
    volumes:
      - "./custom-init:/etc/cont-init.d:ro"
      - "./resilio-config.conf:/config/sync-base.conf:ro"
      - "${RESILIO_SYNC_FOLDER}:/sync:z"

volumes:
  resilio-data:
