services:
  eti-sync-server:
    image: ghcr.io/poeschl/eti-sync-server
    depends_on:
      - resilio
    volumes:
      - ./eti-config.conf:/root/eti-config.conf

      # Keep this line in sync with the data directory in the resilio container
      - resilio-data:/sync:z
      #- ./resilio-data:/sync:z

  resilio:
    image: linuxserver/resilio-sync:2.8.1
    # use the host_network or the ports. It's up to you.
    #network_mode: host
    ports:
      - 8888:8888
      - 55555:55555
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
    volumes:
      - ./resilio-config.conf:/config/sync.conf

      # Keep this line to let docker take care of the data directory
      - resilio-data:/sync:z
      # Otherwise use the next line to keep the data directory in the current directory
      #- ./resilio-data:/sync:z

volumes:
  resilio-data:
